---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator
  namespace: mysql-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-agent
  namespace: mysql-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-operator
  namespace: mysql-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
      - create

  - apiGroups: [""]
    resources:
      - services
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch

  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - update
      - patch

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: ["mysql.oracle.com"]
    resources:
      - mysqlbackups
      - mysqlbackupschedules
      - mysqlclusters
      - mysqlclusters/finalizers
      - mysqlrestores
    verbs:
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: ["mysql.oracle.com"]
    resources: ["mysqlbackups"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mysql-agent
  namespace: mysql-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - update
      - patch

  - apiGroups: ["mysql.oracle.com"]
    resources:
      - mysqlbackups
      - mysqlbackupschedules
      - mysqlclusters
      - mysqlclusters/finalizers
      - mysqlrestores
    verbs:
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: mysql-operator
  namespace: mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql-operator
subjects:
  - kind: ServiceAccount
    name: mysql-operator
    namespace: mysql-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mysql-agent
  namespace: mysql-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql-agent
subjects:
  - kind: ServiceAccount
    name: mysql-agent
    namespace: mysql-operator