kind: ServiceAccount
apiVersion: v1
metadata:
  name: kafka-operator-operator
  namespace: kafka-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/version: 0.8.1
imagePullSecrets: []
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-operator-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/version: 0.8.1
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - apps
    resources:
      - deployments/status
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
    apiGroups:
      - kafka.banzaicloud.io
    resources:
      - kafkaclusters
      - kafkatopics
      - kafkausers
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - kafka.banzaicloud.io
    resources:
      - kafkaclusters/status
      - kafkatopics/status
      - kafkausers/status
  - verbs:
      - get
      - update
      - create
      - watch
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - get
      - update
      - create
      - watch
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - cert-manager.io
    resources:
      - issuers
      - clusterissuers
      - certificates
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafka-operator-operator
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/version: 0.8.1
subjects:
  - kind: ServiceAccount
    name: kafka-operator-operator
    namespace: kafka-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-operator-operator

