definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/mysql:
    post:
      parameters:
      - description: Namespace
        in: query
        name: namespace
        required: true
        type: string
      - description: ClusterName
        in: query
        name: cluster_name
        required: true
        type: string
      - description: User
        in: query
        name: user
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      - description: StorageType
        in: query
        name: storage_type
        required: true
        type: string
      - description: multiMaster
        in: query
        name: multi_master
        required: true
        type: boolean
      - description: Version
        in: query
        name: version
        type: string
      - description: port
        in: query
        name: port
        type: integer
      - description: VolumeSize
        in: query
        name: volume_size
        type: string
      - description: DefaultAuthenticationPlugin
        in: query
        name: default_authentication_plugin
        type: string
      - description: CPU
        in: query
        name: cpu
        type: string
      - description: Memory
        in: query
        name: memory
        type: string
      - description: MaxConnections
        in: query
        name: max_connections
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: add mysql cluster
  /api/v1/mysql/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete mysql cluster
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get a single mysql cluster
  /api/v1/mysqls:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get all mysql cluster
swagger: "2.0"
